name       : xmonad
version    : '0.15'
release    : 3
source     :
    - https://hackage.haskell.org/package/xmonad-0.15/xmonad-0.15.tar.gz : 4a7948e6eee5e34a27d15444589ade3b3fa1adecadbf37b943cff8348380f928
license    : BSD-3-Clause
component  : desktop
summary    : xmonad is a tiling window manager for X.
description: |
    xmonad is a tiling window manager for X. Windows are arranged automatically to tile the screen without gaps or overlap, maximising screen use. Window manager features are accessible from the keyboard: a mouse is optional. xmonad is written, configured and extensible in Haskell. Custom layout algorithms, key bindings and other extensions may be written by the user in config files. Layouts are applied dynamically, and different layouts may be used on each workspace. Xinerama is fully supported, allowing windows to be tiled on several physical screens.
builddeps  :
    - haskell-cabal-install
    - haskell-extensible-exceptions-devel
    - haskell-setlocale-devel
    - haskell-utf8-string-devel
    - haskell-x11-devel
rundeps    :
    - devel:
        - haskell-extensible-exceptions-devel
        - haskell-setlocale-devel
        - haskell-utf8-string-devel
        - haskell-x11-devel
networking : yes
setup      : |
    sed -i 's|"--make"|"--make" , "-dynamic"|' src/XMonad/Core.hs
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
    install -Dm 00644 man/xmonad.1 $installdir/usr/share/man/man1/xmonad.1
