name       : xmonad
version    : 0.17.2
release    : 5
source     :
    - https://hackage.haskell.org/package/xmonad-0.17.2/xmonad-0.17.2.tar.gz : 343277e38d273e12d4e25b44d29875b590a30b51cc228c01fbf69c31844a1fa7
license    : BSD-3-Clause
component  : desktop
summary    : A dynamically tiling X11 window manager that is written and configured in Haskell
description: |
    xmonad is a tiling window manager for X. Windows are arranged automatically to tile the screen without gaps or overlap, maximising screen use. Window manager features are accessible from the keyboard: a mouse is optional. xmonad is written, configured and extensible in Haskell. Custom layout algorithms, key bindings and other extensions may be written by the user in config files. Layouts are applied dynamically, and different layouts may be used on each workspace. Xinerama is fully supported, allowing windows to be tiled on several physical screens.
builddeps  :
    - ghc-devel
    - haskell-data-default-class-devel
    - haskell-setlocale-devel
    - haskell-x11-devel
rundeps    :
    - ghc-devel
    - haskell-data-default-class-devel
    - haskell-setlocale-devel
    - haskell-x11-devel
patterns   : /*
environment: |
    export LDFLAGS="${LDFLAGS/-Wl,-Bsymbolic-functions/-Wl,-Bsymbolic}"
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
    install -Dm00644 man/xmonad.1 $installdir/usr/share/man/man1/xmonad.1
    install -Dm00644 $pkgfiles/xmonad.desktop $installdir/usr/share/xsessions/xmonad.desktop
