name       : xmonad
version    : 0.13
release    : 2
source     :
    - https://hackage.haskell.org/package/xmonad-0.13/xmonad-0.13.tar.gz : f9f81b63569f18c777a939741024ec3ae34e4ec84015e5cc50f6622034a303ca
license    : BSD-3-Clause
component  : desktop
summary    : xmonad is a tiling window manager for X.
description: |
    xmonad is a tiling window manager for X. Windows are arranged automatically to tile the screen without gaps or overlap, maximising screen use. Window manager features are accessible from the keyboard: a mouse is optional. xmonad is written, configured and extensible in Haskell. Custom layout algorithms, key bindings and other extensions may be written by the user in config files. Layouts are applied dynamically, and different layouts may be used on each workspace. Xinerama is fully supported, allowing windows to be tiled on several physical screens.
builddeps  :
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - haskell-cabal-install
    - haskell-extensible-exceptions
    - haskell-mtl
    - haskell-setlocale
    - haskell-utf8-string
    - haskell-x11-devel
setup      : |
    sed -i "s|1.9|1.10|g" xmonad.cabal
    sed -i 's|"--make"|"--make" , "-dynamic"|' src/XMonad/Core.hs
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
    install -Dm 00644 man/xmonad.1 $installdir/usr/share/man/man1/xmonad.1
