name       : xmonad
version    : 0.17.1
release    : 4
source     :
    - https://hackage.haskell.org/package/xmonad-0.17.1/xmonad-0.17.1.tar.gz : 884a32837e41410bab622b26a4b5dc38bd88f1b78a6efd5c552f1456b1e7f8aa
license    : BSD-3-Clause
component  : desktop
summary    : xmonad is a tiling window manager for X.
description: |
    xmonad is a tiling window manager for X. Windows are arranged automatically to tile the screen without gaps or overlap, maximising screen use. Window manager features are accessible from the keyboard: a mouse is optional. xmonad is written, configured and extensible in Haskell. Custom layout algorithms, key bindings and other extensions may be written by the user in config files. Layouts are applied dynamically, and different layouts may be used on each workspace. Xinerama is fully supported, allowing windows to be tiled on several physical screens.
builddeps  :
    - haskell-cabal-install
    - haskell-setlocale-devel
    - haskell-x11-devel
rundeps    :
    - devel :
        - haskell-setlocale-devel
        - haskell-x11-devel
networking : yes
setup      : |
    sed -i 's|"--make"|"--make" , "-dynamic"|' src/XMonad/Core.hs
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
    install -Dm00644 man/xmonad.1 $installdir/usr/share/man/man1/xmonad.1
    install -Dm00644 $pkgfiles/xmonad.desktop $installdir/usr/share/xsessions/xmonad.desktop
